// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAMIX3HBH2joKi0Q-WkpENhWMUGdnH5YY',
    appId: '1:1084838992102:web:9c1a6ee1ee470a523dc327',
    messagingSenderId: '1084838992102',
    projectId: 'electrion-bill',
    authDomain: 'electrion-bill.firebaseapp.com',
    storageBucket: 'electrion-bill.firebasestorage.app',
    measurementId: 'G-FG7M6806ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV04hvz_5xOFjIs-IzC5P0neJmybhP_sA',
    appId: '1:1084838992102:android:0545f78d690a30b93dc327',
    messagingSenderId: '1084838992102',
    projectId: 'electrion-bill',
    storageBucket: 'electrion-bill.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnCygFKiA8OtBiDY0aCqvwy1U9xyclqYs',
    appId: '1:1084838992102:ios:e9d5c157833591ec3dc327',
    messagingSenderId: '1084838992102',
    projectId: 'electrion-bill',
    storageBucket: 'electrion-bill.firebasestorage.app',
    iosBundleId: 'com.example.electritionBill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnCygFKiA8OtBiDY0aCqvwy1U9xyclqYs',
    appId: '1:1084838992102:ios:e9d5c157833591ec3dc327',
    messagingSenderId: '1084838992102',
    projectId: 'electrion-bill',
    storageBucket: 'electrion-bill.firebasestorage.app',
    iosBundleId: 'com.example.electritionBill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAMIX3HBH2joKi0Q-WkpENhWMUGdnH5YY',
    appId: '1:1084838992102:web:7424971299e02b453dc327',
    messagingSenderId: '1084838992102',
    projectId: 'electrion-bill',
    authDomain: 'electrion-bill.firebaseapp.com',
    storageBucket: 'electrion-bill.firebasestorage.app',
    measurementId: 'G-57E6T9S1V7',
  );
}
